---
name: 'Kitsu CI'

on: [push, pull_request]

jobs:
  ci:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, current]
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install npm dependencies
        run: |
          echo "Node.js $(node -v)"
          echo "npm v$(npm -v)"
          npm ci
      - name: Run linter
        if: ${{ matrix.node == 'current' }}
        env:
          NODE_ENV: production
        run: |
          npm run lint -- --quiet
      - name: Run tests
        run: |
          npm run test:unit
      - name: Build application
        run: |
          npm run build
