---
name: "Kitsu CI"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    name: Test with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        run: |
          npm ci
          npm run lint -- --quiet
          npm run test:unit
